In [1]:
pip install numpy



SyntaxError: invalid syntax (4265594094.py, line 1)

In [2]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array(12)
arr3=np.array([[[1,2],[2,3]],[[5,6],[6,7]]])
print(arr3)

[[[1 2]
  [2 3]]

 [[5 6]
  [6 7]]]


In [3]:
import numpy as np
array1=np.array([[1,4,5],[2,3,4],[3,4,5]])
array2=np.array([[1,3,4],[4,5,6],[5,6,6]])
array4=np.multiply(array1,array2)
print(array4)

[[ 1 12 20]
 [ 8 15 24]
 [15 24 30]]


In [4]:
import numpy as np
a=np.array([[4,5,np.nan],[2,3,np.nan]])
res=np.isnan(a)
print(res)

[[False False  True]
 [False False  True]]


In [5]:
import numpy as np
a1=np.array([1,2,3,4,5,6])
a2=np.array([5,6,7,8,9,0])
res=np.in1d(a1,a2)
print(res)
a3=np.array([1,2,3,4,5,6])
a4=np.array([1,2,3,4,5,0])
res2=np.in1d(a3,a4)
print(res2)

[False False False False  True  True]
[ True  True  True  True  True False]


In [6]:
import numpy as np
x=np.linspace(2.5,2.6,30)
print("The array is",x)

The array is [2.5        2.50344828 2.50689655 2.51034483 2.5137931  2.51724138
 2.52068966 2.52413793 2.52758621 2.53103448 2.53448276 2.53793103
 2.54137931 2.54482759 2.54827586 2.55172414 2.55517241 2.55862069
 2.56206897 2.56551724 2.56896552 2.57241379 2.57586207 2.57931034
 2.58275862 2.5862069  2.58965517 2.59310345 2.59655172 2.6       ]


In [8]:
import numpy as np
a5=np.array([1,2,4,5,6])
np.savetxt('test.txt',a5)